### PR TITLE
Frontend rework

### PR DESCRIPTION
**Pull request by setnicka**
This humongous patch separates download core from the frontend. It will make any new frontends (web, …) and batch usage of the ulozto-downloader much more easy to make.

Previously every worker writes to the console independently (only targeting the right console row). Now every worker saves data in the DownloadPart struct, from where teh data is taken by some frontend.

Frontend is injected as dependency using Frontend abstract class which defines API interface between core and the frontend. It is not yet stable, some changes will be probably needed in the future. Now only the ConsoleFrontend is implemented.

It would be nice to refactor it using ncurses (it is possible now, because only one process writes to the console).

Also CaptchaSolver abstract class was developed, primarily to allow easy passing of the log func for the CAPTCHA part. As side effect it also provides nice defined API :)

### CODE REVIEW

**Comment by SpiReCZ** [comment]
I made some similar change here: [ulozto-streamer](https://github.com/setnicka/ulozto-downloader/compare/master...SpiReCZ:ulozto-streamer:ulozto-streamer), but my goal was to make minimal changes to the original codebase, so it can be updated later from this repository. The result was functional, but it`s still CMD-line app first.

**Comment by SpiReCZ** [comment]
Oh, i would almost forgot... Some of my changes make it possible to sequentially stream partially/fully downloaded file. This is useful for REST API when my NAS downloads the file from ulozto-streamer. It might be a good idea to make a pull request of this functionality when these changes here are finished.

**Comment by setnicka** [comment]
I tested this rework on both Linux (Python 3.7, 3.9 and 3.10) and on Windows (Python 3.7 and 3.10) and it finally works fine on all platforms. Will merge it now and make a new pip version from it.

**Comment by setnicka** [comment]
> Oh, i would almost forgot... Some of my changes make it possible to sequentially stream partially/fully downloaded file. This is useful for REST API when my NAS downloads the file from ulozto-streamer. It might be a good idea to make a pull request of this functionality when these changes here are finished.

Pull request with these features would be nice. I hope that this frontend rework wouldn't make the merging impossible hard... but I feel this rework had to be done for future changes.

**Pull request merged**
